### ISSUE TITLE
Add GeoDjango and PostGIS

### ISSUE THREAD

**Issue by jirik** [gis4dis/poster_obsolete#10]
This issue is prerequisite for
- https://github.com/gis4dis/poster/issues/8
- https://github.com/gis4dis/poster/issues/5

**Comment by Darkless012** [comment]
Closed by https://github.com/gis4dis/poster/commit/7c5699888bdb0e199a340b122ff44055483b5006

**Comment by Darkless012** [comment]
Closed by https://github.com/gis4dis/poster/commit/7c5699888bdb0e199a340b122ff44055483b5006
