### ISSUE TITLE
Collect logs from Povodi Moravy

### ISSUE THREAD

**Issue by jirik** [gis4dis/poster_obsolete#12]
FTP access: `/opt/poster-app/data/pmo/access.txt`

We need to collect following five files:

File | Minimum frequency of collecting
--- | ---
`HOD.dat` | once per 7 days
`jakost.dat` | once per 7 days
~~`nadrzesae.txt`~~ | ~~once per day~~ (file is not updated)
~~`nadrzeweb.txt`~~ | ~~once per day~~ (file is not updated)
`nadrzsae.dat` | once per day
`POD.dat` | once per day
`srazsae.dat` | once per 7 days

**Comment by Darkless012** [comment]
@jirik Should I just collect them and store for later processing? Or process directly like ALA?

**Comment by jirik** [comment]
Please just collect them now. Processing can be done later (I assume that it will take much longer time to implement processing than collecting).
