### ISSUE TITLE
Create (Absctract) Base Classes for Modeling

### ISSUE THREAD

**Issue by Darkless012** [gis4dis/poster_obsolete#20]
https://docs.djangoproject.com/en/1.10/topics/db/models/#field-name-hiding-is-not-permitted

AbstractObservation
AbstractFeature

Property - common
Process - common

**Comment by jirik** [comment]
Implemented by
- https://github.com/gis4dis/poster/commit/91d4445971e7091d7722958da2a880047a43abcf
- https://github.com/gis4dis/poster/commit/14cdbdcb999f695e84e83cff7c06e4cfef665bb4
