### ISSUE TITLE
Error 204 for mobility data

### ISSUE THREAD

**Issue by stampachradim** [gis4dis/poster_obsolete#26]
There are many mobility observations with value "unknown because of HTTP Error 204". It is the same for older data. I am not able to find if it is problem of some ZSJ, It seems that it is random.

**Comment by jirik** [comment]
HTTP Error 204 = differential privacy. It't the same in case of socio-demo data, only socio-demo data have more human-readable explanation now. We will improve it also for mobility data.

**Comment by jirik** [comment]
Fixed by 6097453bd682d61e19ebd7e459c2cfa58d48ff1f
