### ISSUE TITLE
export of mobility and socio demo data 

### ISSUE THREAD

**Issue by stampachradim** [gis4dis/poster_obsolete#27]
Zdenek Stachon asks if there will be possibility to export mobility and socio demo data to some format that would allow analysis (and interpretation) by human. He wants to consult some example of collected data with human geographer (Ondrej Mulicek) and to analyse if ZSJ mobility streams are well suggested and if results allow some interpretation.

**Comment by jirik** [comment]
Sure it's possible, please just be more specific about format and structure. My first suggestion is CSV with columns
- zsj_id_from
- zsj_id_to
- occurrence_type_from (transit, visit, both)
- occurrence_type_to (transit, visit, both)
- uniques_type (all, uniques)
- result

Please feel free to invite Zdenek to github to communicate directly in this issue.

**Comment by jirik** [comment]
Further information about data and columns:
- https://developer.o2.cz/portal/api
- https://developer.o2.cz/portal/doc/mobility

**Comment by jirik** [comment]
Internal note:
https://gist.github.com/mgerring/3645889

**Comment by Darkless012** [comment]
I've added "Streaming" CSV export for Mobility and Sciodemo Observations - it needs a bit of polishing though.
But "done" is better than "perfect", right?

**Comment by jirik** [comment]
@Darkless012 Great, thanks.

I've improved export format and admin appearance of ALA and O2 sociodemo in https://github.com/gis4dis/poster/commit/6a51841f22f13cd34df856ea234d598b8615c1c8

O2 mobility will be improved after migration to commons

**Comment by jirik** [comment]
O2 mobility improved by 6097453bd682d61e19ebd7e459c2cfa58d48ff1f
